# Generated by Django 2.2.2 on 2019-06-18 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitems',
            name='content',
        ),
    ]
