# Generated by Django 2.2.2 on 2019-06-18 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_remove_todoitems_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitems',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
